/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;





/**
 *
 * @author ndavid97
 */
public class Bejelentkezes extends javax.swing.JFrame {

    /**
     * Creates new form Bejelentkezés
     */
    public Bejelentkezes() {
        initComponents();
        setSize(540, 270);
        setTitle("Bejelentkezés");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(this);
       
     
        
        
    }

    public JButton getBtnBejelentkezes() {
        return btnBejelentkezes;
    }

    public JLabel getFelhNevLabel() {
        return felhNevLabel;
    }

    public JDialog getjDialog1() {
        return jDialog1;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getJelszoLabel() {
        return jelszoLabel;
    }

    public JTextField getTfFelhNev() {
        return tfFelhNev;
    }

    public JPasswordField getTfJelszo() {
        return tfJelszo;
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jelszoLabel = new javax.swing.JLabel();
        felhNevLabel = new javax.swing.JLabel();
        tfFelhNev = new javax.swing.JTextField();
        tfJelszo = new javax.swing.JPasswordField();
        btnBejelentkezes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jelszoLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jelszoLabel.setForeground(new java.awt.Color(255, 255, 255));
        jelszoLabel.setLabelFor(tfJelszo);
        jelszoLabel.setText("Jelszó:");
        getContentPane().add(jelszoLabel);
        jelszoLabel.setBounds(110, 120, 50, 19);

        felhNevLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        felhNevLabel.setForeground(new java.awt.Color(255, 255, 255));
        felhNevLabel.setLabelFor(tfFelhNev);
        felhNevLabel.setText("Felhasználó név:");
        getContentPane().add(felhNevLabel);
        felhNevLabel.setBounds(43, 83, 120, 19);
        getContentPane().add(tfFelhNev);
        tfFelhNev.setBounds(190, 70, 175, 30);
        getContentPane().add(tfJelszo);
        tfJelszo.setBounds(190, 110, 175, 31);

        btnBejelentkezes.setText("Bejelentkezés");
        getContentPane().add(btnBejelentkezes);
        btnBejelentkezes.setBounds(240, 170, 120, 32);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/0770_NikeWarehouse_s1-this-one.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 540, 270);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bejelentkezes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bejelentkezes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bejelentkezes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bejelentkezes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new Bejelentkezés().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBejelentkezes;
    private javax.swing.JLabel felhNevLabel;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jelszoLabel;
    private javax.swing.JTextField tfFelhNev;
    private javax.swing.JPasswordField tfJelszo;
    // End of variables declaration//GEN-END:variables
}
