/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author ndavid97
 */
public class BejelentkezesDialog extends javax.swing.JDialog {

    /**
     * Creates new form BejelentkezesDialog
     */
    public BejelentkezesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JButton getBtnBejelentkezés() {
        return btnBejelentkezés;
    }

    public JLabel getFelhnévLabel() {
        return felhnévLabel;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

//    public JLabel getjLabel2() {
//        return jLabel2;
//    }

    public JLabel getJelszóLabel() {
        return jelszóLabel;
    }

    public JTextField getTfFelhNév() {
        return tfFelhNév;
    }

    public JPasswordField getTfJelszó() {
        return tfJelszó;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jelszóLabel = new javax.swing.JLabel();
        felhnévLabel = new javax.swing.JLabel();
        tfFelhNév = new javax.swing.JTextField();
        tfJelszó = new javax.swing.JPasswordField();
        btnBejelentkezés = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/0770_NikeWarehouse_s1-this-one.jpg"))); // NOI18N

        jelszóLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jelszóLabel.setForeground(new java.awt.Color(255, 255, 255));
        jelszóLabel.setText("Jelszó:");

        felhnévLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        felhnévLabel.setForeground(new java.awt.Color(255, 255, 255));
        felhnévLabel.setText("Felhasználó név:");

        btnBejelentkezés.setText("Bejelentkezés");
        btnBejelentkezés.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBejelentkezésActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(felhnévLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jelszóLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(tfJelszó, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(tfFelhNév, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(btnBejelentkezés, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(felhnévLabel)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jelszóLabel))
                    .addComponent(tfJelszó, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(tfFelhNév, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(btnBejelentkezés))
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBejelentkezésActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBejelentkezésActionPerformed

//        if (!tfFelhNév.getText().isEmpty() && !tfJelszó.getText().equals("")){
//            JOptionPane.showMessageDialog(this, "Sikeres bejelentkezés", "Siker!", JOptionPane.INFORMATION_MESSAGE);
//            String jogosultság=cbJog.getSelectedItem().toString();
//            switch(jogosultság){
//                case "Admin":new adminKliens().setVisible(true);break;
//                case "Felhasználó":JOptionPane.showMessageDialog(this, "Nincs ilyen kliens", "Hiba",JOptionPane.ERROR_MESSAGE);break;
//                default:;
//
//            }
//            dispose();
//        }
//        else{
//            String hibaÜzenet="Hibás jelszó vagy felhasználó név";
//            JOptionPane.showMessageDialog(this, "hibaÜzenet", "Hiba!", JOptionPane.ERROR_MESSAGE);
//        }

    }//GEN-LAST:event_btnBejelentkezésActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BejelentkezesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BejelentkezesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BejelentkezesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BejelentkezesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                BejelentkezesDialog dialog = new BejelentkezesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBejelentkezés;
    private javax.swing.JLabel felhnévLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jelszóLabel;
    private javax.swing.JTextField tfFelhNév;
    private javax.swing.JPasswordField tfJelszó;
    // End of variables declaration//GEN-END:variables
}
