/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author ndavid97
 */
public class JelentesDialog extends javax.swing.JDialog {

    /**
     * Creates new form JelentesDialog
     */
    public JelentesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setResizable(false);
        setTitle("Jelentések generálása");
    }

    public JCheckBox getJcBeszerzes() {
        return jcBeszerzes;
    }

    public JButton getBtnGeneralPdf() {
        return btnGeneralPdf;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public JCheckBox getJcbBeszallitoTop5() {
        return jcbBeszallitoTop5;
    }

    public JCheckBox getJcbBevetelHavi() {
        return jcbBevetelHavi;
    }

    public JCheckBox getJcbBevetelNegyedEv() {
        return jcbBevetelNegyedEv;
    }

    public JCheckBox getJcbKeszletBecsles() {
        return jcbKeszletBecsles;
    }

    public JCheckBox getJcbRaktarKeszlet() {
        return jcbRaktarKeszlet;
    }

    public JCheckBox getJcbTermekTop5() {
        return jcbTermekTop5;
    }

    public JCheckBox getJcbVasarloTop5() {
        return jcbVasarloTop5;
    }

  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jcbBevetelHavi = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jcbVasarloTop5 = new javax.swing.JCheckBox();
        jcbRaktarKeszlet = new javax.swing.JCheckBox();
        jcbBevetelNegyedEv = new javax.swing.JCheckBox();
        jcbBeszallitoTop5 = new javax.swing.JCheckBox();
        jcbKeszletBecsles = new javax.swing.JCheckBox();
        btnGeneralPdf = new javax.swing.JButton();
        jcbTermekTop5 = new javax.swing.JCheckBox();
        jcBeszerzes = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jcbBevetelHavi.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jcbBevetelHavi.setText("Havi bevételek");

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Válassza ki azokat a kimutatásokat amelyeket látni kíván a PDF-ben");

        jcbVasarloTop5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jcbVasarloTop5.setText("Top 5 legtöbbet vásárló");

        jcbRaktarKeszlet.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jcbRaktarKeszlet.setText("Raktár készlet");

        jcbBevetelNegyedEv.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jcbBevetelNegyedEv.setText("Negyedéves bevételek");

        jcbBeszallitoTop5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jcbBeszallitoTop5.setText("Top 5 legtöbbet beszállító");

        jcbKeszletBecsles.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jcbKeszletBecsles.setText("Készlet ár becslés");

        btnGeneralPdf.setText("PDF generálása");

        jcbTermekTop5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jcbTermekTop5.setText("Top 5 legnépszerűbb termék");

        jcBeszerzes.setText("Beszerzés");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbBevetelHavi)
                    .addComponent(jcbRaktarKeszlet)
                    .addComponent(jcbTermekTop5)
                    .addComponent(jcbVasarloTop5)
                    .addComponent(jcbBeszallitoTop5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbBevetelNegyedEv)
                    .addComponent(btnGeneralPdf)
                    .addComponent(jcbKeszletBecsles)
                    .addComponent(jcBeszerzes))
                .addGap(222, 222, 222))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(jLabel1)
                .addGap(0, 164, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbBevetelHavi)
                    .addComponent(jcbBevetelNegyedEv))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbRaktarKeszlet)
                    .addComponent(jcbKeszletBecsles))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTermekTop5)
                    .addComponent(jcBeszerzes))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jcbVasarloTop5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnGeneralPdf)))
                .addGap(43, 43, 43)
                .addComponent(jcbBeszallitoTop5)
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JelentesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JelentesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JelentesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JelentesDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JelentesDialog dialog = new JelentesDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeneralPdf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox jcBeszerzes;
    private javax.swing.JCheckBox jcbBeszallitoTop5;
    private javax.swing.JCheckBox jcbBevetelHavi;
    private javax.swing.JCheckBox jcbBevetelNegyedEv;
    private javax.swing.JCheckBox jcbKeszletBecsles;
    private javax.swing.JCheckBox jcbRaktarKeszlet;
    private javax.swing.JCheckBox jcbTermekTop5;
    private javax.swing.JCheckBox jcbVasarloTop5;
    // End of variables declaration//GEN-END:variables
}
