/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Frame;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author ndavid97
 */
public class termekUrlap extends javax.swing.JDialog {

    /**
     * Creates new form termekUrlap
     
     */
    public termekUrlap(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
//        setModal(true);
//setModalityType(ModalityType.);
        initComponents();
            
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JComboBox<String> getScrKategoria() {
        return scrKategoria;
    }

    public JTextArea getTareaLeírás() {
        return taLeiras;
    }

    public JTextField getTfEgysegAr() {
        return tfEgysegAr;
    }

    public JTextField getTfMennyiseg() {
        return tfMennyiseg;
    }

    public JTextField getTfNev() {
        return tfNév;
    }

    public JLabel getJlEgysegar() {
        return jlEgysegar;
    }

    public JLabel getJlKategoria() {
        return jlKategoria;
    }

    public JLabel getJlLeiras() {
        return jlLeiras;
    }

    public JLabel getJlMennyiseg() {
        return jlMennyiseg;
    }

    public JLabel getJlTnev() {
        return jlTnev;
    }

    public JTextArea getTaLeírás() {
        return taLeiras;
    }

    public JLabel getIdLbl() {
        return idLbl;
    }

    public JLabel getjLabel9() {
        return jLabel9;
    }


  

    public JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlTnev = new javax.swing.JLabel();
        tfNév = new javax.swing.JTextField();
        jlEgysegar = new javax.swing.JLabel();
        tfEgysegAr = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taLeiras = new javax.swing.JTextArea();
        jlLeiras = new javax.swing.JLabel();
        jlMennyiseg = new javax.swing.JLabel();
        tfMennyiseg = new javax.swing.JTextField();
        jlKategoria = new javax.swing.JLabel();
        scrKategoria = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        idLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlTnev.setText("Termék név:");
        jPanel1.add(jlTnev, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        jPanel1.add(tfNév, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 143, -1));

        jlEgysegar.setText("Egységár:");
        jPanel1.add(jlEgysegar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));
        jPanel1.add(tfEgysegAr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 143, -1));

        taLeiras.setColumns(20);
        taLeiras.setRows(5);
        jScrollPane1.setViewportView(taLeiras);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 176, 117));

        jlLeiras.setText("Leírás:");
        jPanel1.add(jlLeiras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jlMennyiseg.setText("Mennyiség:");
        jPanel1.add(jlMennyiseg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));
        jPanel1.add(tfMennyiseg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 143, -1));

        jlKategoria.setText("Kategória");
        jPanel1.add(jlKategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jPanel1.add(scrKategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 143, -1));

        jLabel9.setText("ID:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));
        jPanel1.add(idLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 109, 24));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//   //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(termekUrlap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(termekUrlap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(termekUrlap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(termekUrlap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//           
//
//        /* Create and display the dialog */
//     java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                termekUrlap dialog = new termekUrlap(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
////                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idLbl;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlEgysegar;
    private javax.swing.JLabel jlKategoria;
    private javax.swing.JLabel jlLeiras;
    private javax.swing.JLabel jlMennyiseg;
    private javax.swing.JLabel jlTnev;
    private javax.swing.JComboBox<String> scrKategoria;
    private javax.swing.JTextArea taLeiras;
    private javax.swing.JTextField tfEgysegAr;
    private javax.swing.JTextField tfMennyiseg;
    private javax.swing.JTextField tfNév;
    // End of variables declaration//GEN-END:variables
}
